//============================================================================
//  V60 CMPC/MOVC fill & stop variants + exact tail registers (op7a.hxx).
//  Auto-generated by scratchpad/gen_strfs_tb.py; expectations come from the
//  str_oracle.py mirror of MAME opCMPSTRB/H and opMOVSTRU*/D* (bFill,bStop).
//============================================================================
`timescale 1ns/1ps
module tb_v60_strfs;
reg clk = 0, rst = 1;
always #10 clk = ~clk;
wire        c_req, c_we, c_ack;
wire [31:0] c_addr, c_wdata, c_rdata;
wire [1:0]  c_size;
wire        m_req, m_we, m_ack;
wire [23:1] m_addr;
wire [15:0] m_wdata, m_rdata;
wire [1:0]  m_be;
s32_v60 #(.START_PC(32'h0)) cpu (
    .clk(clk), .ce(1'b1), .rst(rst),
    .if_req(), .if_addr(), .if_data(64'd0), .if_ack(1'b0),
    .bus_req(c_req), .bus_we(c_we), .bus_addr(c_addr), .bus_size(c_size),
    .bus_wdata(c_wdata), .bus_rdata(c_rdata), .bus_ack(c_ack),
    .irq_n(1'b1), .irq_vector(8'h00), .irq_ack(), .nmi_n(1'b1),
    .dbg_pc(), .dbg_halted());
s32_v60_bus adapter (
    .clk(clk), .ce(1'b1), .rst(rst), .v70_mode(1'b0),
    .c_req(c_req), .c_we(c_we), .c_addr(c_addr), .c_size(c_size),
    .c_wdata(c_wdata), .c_rdata(c_rdata), .c_ack(c_ack),
    .m_req(m_req), .m_we(m_we), .m_addr(m_addr), .m_wdata(m_wdata),
    .m_be(m_be), .m_rdata(m_rdata), .m_ack(m_ack));
reg [15:0] ram [0:32767];
reg ack_r = 1'b0;
assign m_rdata = ram[m_addr[15:1]];
assign m_ack = ack_r;
integer i, wd, errors = 0;
always @(posedge clk) begin
    if (rst) ack_r <= 1'b0;
    else begin
        ack_r <= m_req && !ack_r;
        if (m_req && m_we && !ack_r) begin
            if (m_be[0]) ram[m_addr[15:1]][7:0]  <= m_wdata[7:0];
            if (m_be[1]) ram[m_addr[15:1]][15:8] <= m_wdata[15:8];
        end
    end
end
task automatic check(input condition, input [255:0] nm);
    if (condition !== 1'b1) begin errors = errors + 1; $display("  FAIL: %0s", nm); end
endtask
task automatic put_el(input integer a, input [15:0] v);
    if (a[0]) ram[a>>1][15:8] = v[7:0]; else ram[a>>1][7:0] = v[7:0];
    // high byte of a halfword element lands at a+1
    if (a[0]) ram[(a+1)>>1][7:0] = v[15:8]; else ram[a>>1][15:8] = v[15:8];
endtask
function [7:0] gb(input integer a);
    gb = a[0] ? ram[a>>1][15:8] : ram[a>>1][7:0];
endfunction
task automatic clear_ram; for (i=0;i<32768;i=i+1) ram[i] = 16'h0000; endtask
// Seed the CPU directly at S_STR_OP2 and let the string engine run to S_NEXT.
task automatic run_case(input [7:0] opb, input [7:0] sub,
                        input integer o1, input integer o2,
                        input integer l1, input integer l2, input [15:0] r26);
    @(negedge clk);
    rst = 1'b1; repeat(2) @(posedge clk); @(negedge clk);
    cpu.st = cpu.S_STR_OP2;
    cpu.cur_op = opb;
    cpu.subop  = sub;
    cpu.op1 = o1; cpu.op2 = o2;
    cpu.str_src = o1;    // S_STR_OP1 normally seeds this; we enter at S_STR_OP2
    cpu.str_dst = o2;
    cpu.str_len1 = l1;
    cpu.len1 = 0; cpu.len2 = 0;
    cpu.fb[3] = l2[7:0];
    cpu.r[26] = {16'b0, r26};
    cpu.dbus_req = 1'b0; cpu.dbus_we = 1'b0;
    rst = 1'b0;
    wd = 0;
    while ((cpu.st !== cpu.S_NEXT) && (wd < 4000)) begin @(posedge clk); #1; wd = wd + 1; end
    check(wd < 4000, "case completes");
endtask
initial begin
    clear_ram();
    // ---- MOVCU_eq  exp R28=4100 R27=8196 ----
    clear_ram();
    put_el(4096, 16'h0057);
    put_el(4097, 16'h0058);
    put_el(4098, 16'h0059);
    put_el(4099, 16'h005a);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8195, 16'h0000);
    run_case(8'h58, 8'h08, 4096, 8192, 4, 4, 16'h0000);
    check(gb(4096)==87, "MOVCU_eq mem[0x1000]");
    check(gb(4097)==88, "MOVCU_eq mem[0x1001]");
    check(gb(4098)==89, "MOVCU_eq mem[0x1002]");
    check(gb(4099)==90, "MOVCU_eq mem[0x1003]");
    check(gb(8192)==87, "MOVCU_eq mem[0x2000]");
    check(gb(8193)==88, "MOVCU_eq mem[0x2001]");
    check(gb(8194)==89, "MOVCU_eq mem[0x2002]");
    check(gb(8195)==90, "MOVCU_eq mem[0x2003]");
    check(cpu.r[28]==4100, "MOVCU_eq R28");
    check(cpu.r[27]==8196, "MOVCU_eq R27");

    // ---- MOVCU_s<d  exp R28=4098 R27=8194 ----
    clear_ram();
    put_el(4096, 16'h0011);
    put_el(4097, 16'h0022);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8195, 16'h0000);
    put_el(8196, 16'h0000);
    run_case(8'h58, 8'h08, 4096, 8192, 2, 5, 16'h0000);
    check(gb(4096)==17, "MOVCU_s<d mem[0x1000]");
    check(gb(4097)==34, "MOVCU_s<d mem[0x1001]");
    check(gb(8192)==17, "MOVCU_s<d mem[0x2000]");
    check(gb(8193)==34, "MOVCU_s<d mem[0x2001]");
    check(gb(8194)==0, "MOVCU_s<d mem[0x2002]");
    check(gb(8195)==0, "MOVCU_s<d mem[0x2003]");
    check(gb(8196)==0, "MOVCU_s<d mem[0x2004]");
    check(cpu.r[28]==4098, "MOVCU_s<d R28");
    check(cpu.r[27]==8194, "MOVCU_s<d R27");

    // ---- MOVCU_s>d  exp R28=4098 R27=8194 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0003);
    put_el(4099, 16'h0004);
    put_el(4100, 16'h0005);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    run_case(8'h58, 8'h08, 4096, 8192, 5, 2, 16'h0000);
    check(gb(4096)==1, "MOVCU_s>d mem[0x1000]");
    check(gb(4097)==2, "MOVCU_s>d mem[0x1001]");
    check(gb(4098)==3, "MOVCU_s>d mem[0x1002]");
    check(gb(4099)==4, "MOVCU_s>d mem[0x1003]");
    check(gb(4100)==5, "MOVCU_s>d mem[0x1004]");
    check(gb(8192)==1, "MOVCU_s>d mem[0x2000]");
    check(gb(8193)==2, "MOVCU_s>d mem[0x2001]");
    check(cpu.r[28]==4098, "MOVCU_s>d R28");
    check(cpu.r[27]==8194, "MOVCU_s>d R27");

    // ---- MOVCD_eq  exp R28=4095 R27=8191 ----
    clear_ram();
    put_el(4096, 16'h0057);
    put_el(4097, 16'h0058);
    put_el(4098, 16'h0059);
    put_el(4099, 16'h005a);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8195, 16'h0000);
    run_case(8'h58, 8'h09, 4096, 8192, 4, 4, 16'h0000);
    check(gb(4096)==87, "MOVCD_eq mem[0x1000]");
    check(gb(4097)==88, "MOVCD_eq mem[0x1001]");
    check(gb(4098)==89, "MOVCD_eq mem[0x1002]");
    check(gb(4099)==90, "MOVCD_eq mem[0x1003]");
    check(gb(8192)==87, "MOVCD_eq mem[0x2000]");
    check(gb(8193)==88, "MOVCD_eq mem[0x2001]");
    check(gb(8194)==89, "MOVCD_eq mem[0x2002]");
    check(gb(8195)==90, "MOVCD_eq mem[0x2003]");
    check(cpu.r[28]==4095, "MOVCD_eq R28");
    check(cpu.r[27]==8191, "MOVCD_eq R27");

    // ---- MOVCD_s<d  exp R28=4095 R27=8194 ----
    clear_ram();
    put_el(4096, 16'h0011);
    put_el(4097, 16'h0022);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8195, 16'h0000);
    put_el(8196, 16'h0000);
    run_case(8'h58, 8'h09, 4096, 8192, 2, 5, 16'h0000);
    check(gb(4096)==17, "MOVCD_s<d mem[0x1000]");
    check(gb(4097)==34, "MOVCD_s<d mem[0x1001]");
    check(gb(8192)==17, "MOVCD_s<d mem[0x2000]");
    check(gb(8193)==34, "MOVCD_s<d mem[0x2001]");
    check(gb(8194)==0, "MOVCD_s<d mem[0x2002]");
    check(gb(8195)==0, "MOVCD_s<d mem[0x2003]");
    check(gb(8196)==0, "MOVCD_s<d mem[0x2004]");
    check(cpu.r[28]==4095, "MOVCD_s<d R28");
    check(cpu.r[27]==8194, "MOVCD_s<d R27");

    // ---- MOVCUh_eq  exp R28=4102 R27=8198 ----
    clear_ram();
    put_el(4096, 16'h1234);
    put_el(4098, 16'h5678);
    put_el(4100, 16'h9abc);
    put_el(8192, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8196, 16'h0000);
    run_case(8'h5a, 8'h08, 4096, 8192, 3, 3, 16'h0000);
    check(gb(4096)==52, "MOVCUh_eq mem[0x1000]");
    check(gb(4097)==18, "MOVCUh_eq mem[0x1001]");
    check(gb(4098)==120, "MOVCUh_eq mem[0x1002]");
    check(gb(4099)==86, "MOVCUh_eq mem[0x1003]");
    check(gb(4100)==188, "MOVCUh_eq mem[0x1004]");
    check(gb(4101)==154, "MOVCUh_eq mem[0x1005]");
    check(gb(8192)==52, "MOVCUh_eq mem[0x2000]");
    check(gb(8193)==18, "MOVCUh_eq mem[0x2001]");
    check(gb(8194)==120, "MOVCUh_eq mem[0x2002]");
    check(gb(8195)==86, "MOVCUh_eq mem[0x2003]");
    check(gb(8196)==188, "MOVCUh_eq mem[0x2004]");
    check(gb(8197)==154, "MOVCUh_eq mem[0x2005]");
    check(cpu.r[28]==4102, "MOVCUh_eq R28");
    check(cpu.r[27]==8198, "MOVCUh_eq R27");

    // ---- CMPC_eq  exp R28=6 R27=6 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0003);
    put_el(8192, 16'h0001);
    put_el(8193, 16'h0002);
    put_el(8194, 16'h0003);
    run_case(8'h58, 8'h00, 4096, 8192, 3, 3, 16'h0000);
    check(gb(4096)==1, "CMPC_eq mem[0x1000]");
    check(gb(4097)==2, "CMPC_eq mem[0x1001]");
    check(gb(4098)==3, "CMPC_eq mem[0x1002]");
    check(gb(8192)==1, "CMPC_eq mem[0x2000]");
    check(gb(8193)==2, "CMPC_eq mem[0x2001]");
    check(gb(8194)==3, "CMPC_eq mem[0x2002]");
    check(cpu.r[28]==6, "CMPC_eq R28");
    check(cpu.r[27]==6, "CMPC_eq R27");
    check(cpu.f_z==1, "CMPC_eq Z");
    check(cpu.f_s==0, "CMPC_eq S");

    // ---- CMPC_s>d  exp R28=4 R27=4 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0005);
    put_el(4098, 16'h0003);
    put_el(8192, 16'h0001);
    put_el(8193, 16'h0002);
    put_el(8194, 16'h0003);
    run_case(8'h58, 8'h00, 4096, 8192, 3, 3, 16'h0000);
    check(gb(4096)==1, "CMPC_s>d mem[0x1000]");
    check(gb(4097)==5, "CMPC_s>d mem[0x1001]");
    check(gb(4098)==3, "CMPC_s>d mem[0x1002]");
    check(gb(8192)==1, "CMPC_s>d mem[0x2000]");
    check(gb(8193)==2, "CMPC_s>d mem[0x2001]");
    check(gb(8194)==3, "CMPC_s>d mem[0x2002]");
    check(cpu.r[28]==4, "CMPC_s>d R28");
    check(cpu.r[27]==4, "CMPC_s>d R27");
    check(cpu.f_z==0, "CMPC_s>d Z");
    check(cpu.f_s==1, "CMPC_s>d S");

    // ---- CMPC_s<d  exp R28=4 R27=4 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0003);
    put_el(8192, 16'h0001);
    put_el(8193, 16'h0009);
    put_el(8194, 16'h0003);
    run_case(8'h58, 8'h00, 4096, 8192, 3, 3, 16'h0000);
    check(gb(4096)==1, "CMPC_s<d mem[0x1000]");
    check(gb(4097)==2, "CMPC_s<d mem[0x1001]");
    check(gb(4098)==3, "CMPC_s<d mem[0x1002]");
    check(gb(8192)==1, "CMPC_s<d mem[0x2000]");
    check(gb(8193)==9, "CMPC_s<d mem[0x2001]");
    check(gb(8194)==3, "CMPC_s<d mem[0x2002]");
    check(cpu.r[28]==4, "CMPC_s<d R28");
    check(cpu.r[27]==4, "CMPC_s<d R27");
    check(cpu.f_z==0, "CMPC_s<d Z");
    check(cpu.f_s==0, "CMPC_s<d S");

    // ---- CMPC_len  exp R28=8 R27=6 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0003);
    put_el(4099, 16'h0004);
    put_el(4100, 16'h0005);
    put_el(8192, 16'h0001);
    put_el(8193, 16'h0002);
    put_el(8194, 16'h0003);
    run_case(8'h58, 8'h00, 4096, 8192, 5, 3, 16'h0000);
    check(gb(4096)==1, "CMPC_len mem[0x1000]");
    check(gb(4097)==2, "CMPC_len mem[0x1001]");
    check(gb(4098)==3, "CMPC_len mem[0x1002]");
    check(gb(4099)==4, "CMPC_len mem[0x1003]");
    check(gb(4100)==5, "CMPC_len mem[0x1004]");
    check(gb(8192)==1, "CMPC_len mem[0x2000]");
    check(gb(8193)==2, "CMPC_len mem[0x2001]");
    check(gb(8194)==3, "CMPC_len mem[0x2002]");
    check(cpu.r[28]==8, "CMPC_len R28");
    check(cpu.r[27]==6, "CMPC_len R27");
    check(cpu.f_z==0, "CMPC_len Z");
    check(cpu.f_s==1, "CMPC_len S");

    // ---- CMPCh_s>d  exp R28=5 R27=5 ----
    clear_ram();
    put_el(4096, 16'h0100);
    put_el(4098, 16'h0555);
    put_el(4100, 16'h0300);
    put_el(8192, 16'h0100);
    put_el(8194, 16'h0222);
    put_el(8196, 16'h0300);
    run_case(8'h5a, 8'h00, 4096, 8192, 3, 3, 16'h0000);
    check(gb(4096)==0, "CMPCh_s>d mem[0x1000]");
    check(gb(4097)==1, "CMPCh_s>d mem[0x1001]");
    check(gb(4098)==85, "CMPCh_s>d mem[0x1002]");
    check(gb(4099)==5, "CMPCh_s>d mem[0x1003]");
    check(gb(4100)==0, "CMPCh_s>d mem[0x1004]");
    check(gb(4101)==3, "CMPCh_s>d mem[0x1005]");
    check(gb(8192)==0, "CMPCh_s>d mem[0x2000]");
    check(gb(8193)==1, "CMPCh_s>d mem[0x2001]");
    check(gb(8194)==34, "CMPCh_s>d mem[0x2002]");
    check(gb(8195)==2, "CMPCh_s>d mem[0x2003]");
    check(gb(8196)==0, "CMPCh_s>d mem[0x2004]");
    check(gb(8197)==3, "CMPCh_s>d mem[0x2005]");
    check(cpu.r[28]==5, "CMPCh_s>d R28");
    check(cpu.r[27]==5, "CMPCh_s>d R27");
    check(cpu.f_z==0, "CMPCh_s>d Z");
    check(cpu.f_s==1, "CMPCh_s>d S");

    // ---- CMPCF_s<d  exp R28=4 R27=7 ----
    clear_ram();
    put_el(4096, 16'h00aa);
    put_el(4097, 16'h00aa);
    put_el(8192, 16'h00aa);
    put_el(8193, 16'h00aa);
    put_el(8194, 16'h00aa);
    put_el(8195, 16'h00aa);
    put_el(8196, 16'h00aa);
    run_case(8'h58, 8'h01, 4096, 8192, 2, 5, 16'h00aa);
    check(gb(4096)==170, "CMPCF_s<d mem[0x1000]");
    check(gb(4097)==170, "CMPCF_s<d mem[0x1001]");
    check(gb(4098)==170, "CMPCF_s<d mem[0x1002]");
    check(gb(4099)==170, "CMPCF_s<d mem[0x1003]");
    check(gb(4100)==170, "CMPCF_s<d mem[0x1004]");
    check(gb(8192)==170, "CMPCF_s<d mem[0x2000]");
    check(gb(8193)==170, "CMPCF_s<d mem[0x2001]");
    check(gb(8194)==170, "CMPCF_s<d mem[0x2002]");
    check(gb(8195)==170, "CMPCF_s<d mem[0x2003]");
    check(gb(8196)==170, "CMPCF_s<d mem[0x2004]");
    check(cpu.r[28]==4, "CMPCF_s<d R28");
    check(cpu.r[27]==7, "CMPCF_s<d R27");
    check(cpu.f_z==0, "CMPCF_s<d Z");
    check(cpu.f_s==0, "CMPCF_s<d S");

    // ---- CMPCF_s>d  exp R28=7 R27=4 ----
    clear_ram();
    put_el(4096, 16'h0007);
    put_el(4097, 16'h0007);
    put_el(4098, 16'h0009);
    put_el(4099, 16'h0009);
    put_el(4100, 16'h0009);
    put_el(8192, 16'h0007);
    put_el(8193, 16'h0007);
    run_case(8'h58, 8'h01, 4096, 8192, 5, 2, 16'h0007);
    check(gb(4096)==7, "CMPCF_s>d mem[0x1000]");
    check(gb(4097)==7, "CMPCF_s>d mem[0x1001]");
    check(gb(4098)==9, "CMPCF_s>d mem[0x1002]");
    check(gb(4099)==9, "CMPCF_s>d mem[0x1003]");
    check(gb(4100)==9, "CMPCF_s>d mem[0x1004]");
    check(gb(8192)==7, "CMPCF_s>d mem[0x2000]");
    check(gb(8193)==7, "CMPCF_s>d mem[0x2001]");
    check(gb(8194)==7, "CMPCF_s>d mem[0x2002]");
    check(gb(8195)==7, "CMPCF_s>d mem[0x2003]");
    check(gb(8196)==7, "CMPCF_s>d mem[0x2004]");
    check(cpu.r[28]==7, "CMPCF_s>d R28");
    check(cpu.r[27]==4, "CMPCF_s>d R27");
    check(cpu.f_z==0, "CMPCF_s>d Z");
    check(cpu.f_s==1, "CMPCF_s>d S");

    // ---- MOVCFU_s<d  exp R28=4098 R27=8197 ----
    clear_ram();
    put_el(4096, 16'h0033);
    put_el(4097, 16'h0044);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8195, 16'h0000);
    put_el(8196, 16'h0000);
    run_case(8'h58, 8'h0a, 4096, 8192, 2, 5, 16'h0099);
    check(gb(4096)==51, "MOVCFU_s<d mem[0x1000]");
    check(gb(4097)==68, "MOVCFU_s<d mem[0x1001]");
    check(gb(8192)==51, "MOVCFU_s<d mem[0x2000]");
    check(gb(8193)==68, "MOVCFU_s<d mem[0x2001]");
    check(gb(8194)==153, "MOVCFU_s<d mem[0x2002]");
    check(gb(8195)==153, "MOVCFU_s<d mem[0x2003]");
    check(gb(8196)==153, "MOVCFU_s<d mem[0x2004]");
    check(cpu.r[28]==4098, "MOVCFU_s<d R28");
    check(cpu.r[27]==8197, "MOVCFU_s<d R27");

    // ---- MOVCFUh  exp R28=4100 R27=8200 ----
    clear_ram();
    put_el(4096, 16'h1111);
    put_el(4098, 16'h2222);
    put_el(8192, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8196, 16'h0000);
    put_el(8198, 16'h0000);
    run_case(8'h5a, 8'h0a, 4096, 8192, 2, 4, 16'hbeef);
    check(gb(4096)==17, "MOVCFUh mem[0x1000]");
    check(gb(4097)==17, "MOVCFUh mem[0x1001]");
    check(gb(4098)==34, "MOVCFUh mem[0x1002]");
    check(gb(4099)==34, "MOVCFUh mem[0x1003]");
    check(gb(8192)==17, "MOVCFUh mem[0x2000]");
    check(gb(8193)==17, "MOVCFUh mem[0x2001]");
    check(gb(8194)==34, "MOVCFUh mem[0x2002]");
    check(gb(8195)==34, "MOVCFUh mem[0x2003]");
    check(gb(8196)==239, "MOVCFUh mem[0x2004]");
    check(gb(8197)==190, "MOVCFUh mem[0x2005]");
    check(gb(8198)==239, "MOVCFUh mem[0x2006]");
    check(gb(8199)==190, "MOVCFUh mem[0x2007]");
    check(cpu.r[28]==4100, "MOVCFUh R28");
    check(cpu.r[27]==8200, "MOVCFUh R27");

    // ---- MOVCFD_s<d  exp R28=4095 R27=8191 ----
    clear_ram();
    put_el(4096, 16'h0033);
    put_el(4097, 16'h0044);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8195, 16'h0000);
    put_el(8196, 16'h0000);
    run_case(8'h58, 8'h0b, 4096, 8192, 2, 5, 16'h0077);
    check(gb(4096)==51, "MOVCFD_s<d mem[0x1000]");
    check(gb(4097)==68, "MOVCFD_s<d mem[0x1001]");
    check(gb(8192)==51, "MOVCFD_s<d mem[0x2000]");
    check(gb(8193)==68, "MOVCFD_s<d mem[0x2001]");
    check(gb(8194)==119, "MOVCFD_s<d mem[0x2002]");
    check(gb(8195)==119, "MOVCFD_s<d mem[0x2003]");
    check(gb(8196)==119, "MOVCFD_s<d mem[0x2004]");
    check(cpu.r[28]==4095, "MOVCFD_s<d R28");
    check(cpu.r[27]==8191, "MOVCFD_s<d R27");

    // ---- CMPCS_hit  exp R28=7 R27=7 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0040);
    put_el(4099, 16'h0004);
    put_el(4100, 16'h0005);
    put_el(8192, 16'h0001);
    put_el(8193, 16'h0002);
    put_el(8194, 16'h0040);
    put_el(8195, 16'h0004);
    put_el(8196, 16'h0005);
    run_case(8'h58, 8'h02, 4096, 8192, 5, 5, 16'h0040);
    check(gb(4096)==1, "CMPCS_hit mem[0x1000]");
    check(gb(4097)==2, "CMPCS_hit mem[0x1001]");
    check(gb(4098)==64, "CMPCS_hit mem[0x1002]");
    check(gb(4099)==4, "CMPCS_hit mem[0x1003]");
    check(gb(4100)==5, "CMPCS_hit mem[0x1004]");
    check(gb(8192)==1, "CMPCS_hit mem[0x2000]");
    check(gb(8193)==2, "CMPCS_hit mem[0x2001]");
    check(gb(8194)==64, "CMPCS_hit mem[0x2002]");
    check(gb(8195)==4, "CMPCS_hit mem[0x2003]");
    check(gb(8196)==5, "CMPCS_hit mem[0x2004]");
    check(cpu.r[28]==7, "CMPCS_hit R28");
    check(cpu.r[27]==7, "CMPCS_hit R27");
    check(cpu.f_z==0, "CMPCS_hit Z");
    check(cpu.f_s==0, "CMPCS_hit S");
    check(cpu.f_cy==0, "CMPCS_hit CY");

    // ---- CMPCS_diff  exp R28=7 R27=7 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0003);
    put_el(4099, 16'h0004);
    put_el(4100, 16'h0005);
    put_el(8192, 16'h0001);
    put_el(8193, 16'h0002);
    put_el(8194, 16'h0009);
    put_el(8195, 16'h0004);
    put_el(8196, 16'h0005);
    run_case(8'h58, 8'h02, 4096, 8192, 5, 5, 16'h0040);
    check(gb(4096)==1, "CMPCS_diff mem[0x1000]");
    check(gb(4097)==2, "CMPCS_diff mem[0x1001]");
    check(gb(4098)==3, "CMPCS_diff mem[0x1002]");
    check(gb(4099)==4, "CMPCS_diff mem[0x1003]");
    check(gb(4100)==5, "CMPCS_diff mem[0x1004]");
    check(gb(8192)==1, "CMPCS_diff mem[0x2000]");
    check(gb(8193)==2, "CMPCS_diff mem[0x2001]");
    check(gb(8194)==9, "CMPCS_diff mem[0x2002]");
    check(gb(8195)==4, "CMPCS_diff mem[0x2003]");
    check(gb(8196)==5, "CMPCS_diff mem[0x2004]");
    check(cpu.r[28]==7, "CMPCS_diff R28");
    check(cpu.r[27]==7, "CMPCS_diff R27");
    check(cpu.f_z==0, "CMPCS_diff Z");
    check(cpu.f_s==0, "CMPCS_diff S");
    check(cpu.f_cy==1, "CMPCS_diff CY");

    // ---- CMPCS_none  exp R28=6 R27=6 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0003);
    put_el(8192, 16'h0001);
    put_el(8193, 16'h0002);
    put_el(8194, 16'h0003);
    run_case(8'h58, 8'h02, 4096, 8192, 3, 3, 16'h0040);
    check(gb(4096)==1, "CMPCS_none mem[0x1000]");
    check(gb(4097)==2, "CMPCS_none mem[0x1001]");
    check(gb(4098)==3, "CMPCS_none mem[0x1002]");
    check(gb(8192)==1, "CMPCS_none mem[0x2000]");
    check(gb(8193)==2, "CMPCS_none mem[0x2001]");
    check(gb(8194)==3, "CMPCS_none mem[0x2002]");
    check(cpu.r[28]==6, "CMPCS_none R28");
    check(cpu.r[27]==6, "CMPCS_none R27");
    check(cpu.f_z==1, "CMPCS_none Z");
    check(cpu.f_s==0, "CMPCS_none S");
    check(cpu.f_cy==1, "CMPCS_none CY");

    // ---- MOVCSU_hit  exp R28=4098 R27=8194 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0055);
    put_el(4099, 16'h0004);
    put_el(4100, 16'h0005);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8195, 16'h0000);
    put_el(8196, 16'h0000);
    run_case(8'h58, 8'h0c, 4096, 8192, 5, 5, 16'h0055);
    check(gb(4096)==1, "MOVCSU_hit mem[0x1000]");
    check(gb(4097)==2, "MOVCSU_hit mem[0x1001]");
    check(gb(4098)==85, "MOVCSU_hit mem[0x1002]");
    check(gb(4099)==4, "MOVCSU_hit mem[0x1003]");
    check(gb(4100)==5, "MOVCSU_hit mem[0x1004]");
    check(gb(8192)==1, "MOVCSU_hit mem[0x2000]");
    check(gb(8193)==2, "MOVCSU_hit mem[0x2001]");
    check(gb(8194)==85, "MOVCSU_hit mem[0x2002]");
    check(gb(8195)==0, "MOVCSU_hit mem[0x2003]");
    check(gb(8196)==0, "MOVCSU_hit mem[0x2004]");
    check(cpu.r[28]==4098, "MOVCSU_hit R28");
    check(cpu.r[27]==8194, "MOVCSU_hit R27");

    // ---- MOVCSU_no  exp R28=4100 R27=8196 ----
    clear_ram();
    put_el(4096, 16'h0001);
    put_el(4097, 16'h0002);
    put_el(4098, 16'h0003);
    put_el(4099, 16'h0004);
    put_el(8192, 16'h0000);
    put_el(8193, 16'h0000);
    put_el(8194, 16'h0000);
    put_el(8195, 16'h0000);
    run_case(8'h58, 8'h0c, 4096, 8192, 4, 4, 16'h0055);
    check(gb(4096)==1, "MOVCSU_no mem[0x1000]");
    check(gb(4097)==2, "MOVCSU_no mem[0x1001]");
    check(gb(4098)==3, "MOVCSU_no mem[0x1002]");
    check(gb(4099)==4, "MOVCSU_no mem[0x1003]");
    check(gb(8192)==1, "MOVCSU_no mem[0x2000]");
    check(gb(8193)==2, "MOVCSU_no mem[0x2001]");
    check(gb(8194)==3, "MOVCSU_no mem[0x2002]");
    check(gb(8195)==4, "MOVCSU_no mem[0x2003]");
    check(cpu.r[28]==4100, "MOVCSU_no R28");
    check(cpu.r[27]==8196, "MOVCSU_no R27");

    // =====================================================================
    // Round 25 audit: zero-length and length-1 edges (hand-derived from
    // op7a.hxx; these exercise the movc_finish(0) path and the down-copy
    // uint32 wrap to base-step that no generated case covered).
    // =====================================================================
    // ---- MOVCU l1=0,l2=4: no copy, R28=op1, R27=op2, dest untouched ----
    clear_ram();
    put_el(4096, 16'h0011);
    put_el(8192, 16'h00aa);
    run_case(8'h58, 8'h08, 4096, 8192, 0, 4, 16'h0000);
    check(gb(8192)==8'haa, "MOVCU_len0 dest untouched");
    check(cpu.r[28]==4096, "MOVCU_len0 R28");
    check(cpu.r[27]==8192, "MOVCU_len0 R27");

    // ---- MOVCU l1=1,l2=1: one byte, R28=op1+1, R27=op2+1 ----
    clear_ram();
    put_el(4096, 16'h0042);
    put_el(8192, 16'h00aa);
    run_case(8'h58, 8'h08, 4096, 8192, 1, 1, 16'h0000);
    check(gb(8192)==8'h42, "MOVCU_len1 copied");
    check(cpu.r[28]==4097, "MOVCU_len1 R28");
    check(cpu.r[27]==8193, "MOVCU_len1 R27");

    // ---- MOVCD l1=0,l2=0: no copy, R28=op1-1, R27=op2-1 (uint32 wrap) ----
    clear_ram();
    put_el(8192, 16'h00aa);
    run_case(8'h58, 8'h09, 4096, 8192, 0, 0, 16'h0000);
    check(gb(8192)==8'haa, "MOVCD_len0 dest untouched");
    check(cpu.r[28]==4095, "MOVCD_len0 R28");
    check(cpu.r[27]==8191, "MOVCD_len0 R27");

    // ---- MOVCD l1=1,l2=1: one byte, R28=op1-1, R27=op2-1 ----
    clear_ram();
    put_el(4096, 16'h0077);
    put_el(8192, 16'h00aa);
    run_case(8'h58, 8'h09, 4096, 8192, 1, 1, 16'h0000);
    check(gb(8192)==8'h77, "MOVCD_len1 copied");
    check(cpu.r[28]==4095, "MOVCD_len1 R28");
    check(cpu.r[27]==8191, "MOVCD_len1 R27");

    // ---- CMPC l1=0,l2=0: Z=1 S=0, R28=len1+i=0, R27=0 ----
    clear_ram();
    run_case(8'h58, 8'h00, 4096, 8192, 0, 0, 16'h0000);
    check(cpu.f_z==1'b1, "CMPC_len0 Z");
    check(cpu.f_s==1'b0, "CMPC_len0 S");
    check(cpu.r[28]==0, "CMPC_len0 R28");
    check(cpu.r[27]==0, "CMPC_len0 R27");

    // ---- CMPC l1=1,l2=1 equal: full run, R28=len1+i=2, R27=2, Z=1 ----
    clear_ram();
    put_el(4096, 16'h0033);
    put_el(8192, 16'h0033);
    run_case(8'h58, 8'h00, 4096, 8192, 1, 1, 16'h0000);
    check(cpu.f_z==1'b1, "CMPC_len1eq Z");
    check(cpu.f_s==1'b0, "CMPC_len1eq S");
    check(cpu.r[28]==2, "CMPC_len1eq R28");
    check(cpu.r[27]==2, "CMPC_len1eq R27");

    // ---- CMPC l1=1,l2=1 c1>c2: break at i=0, R28=1, R27=1, S=1 ----
    clear_ram();
    put_el(4096, 16'h0060);
    put_el(8192, 16'h0040);
    run_case(8'h58, 8'h00, 4096, 8192, 1, 1, 16'h0000);
    check(cpu.f_z==1'b0, "CMPC_len1gt Z");
    check(cpu.f_s==1'b1, "CMPC_len1gt S");
    check(cpu.r[28]==1, "CMPC_len1gt R28");
    check(cpu.r[27]==1, "CMPC_len1gt R27");

    // ---- MOVCFU l1=0,l2=3: pure fill, R28=op1, R27=op2+3 ----
    clear_ram();
    run_case(8'h58, 8'h0a, 4096, 8192, 0, 3, 16'h0055);
    check(gb(8192)==8'h55, "MOVCFU_len0 fill0");
    check(gb(8193)==8'h55, "MOVCFU_len0 fill1");
    check(gb(8194)==8'h55, "MOVCFU_len0 fill2");
    check(cpu.r[28]==4096, "MOVCFU_len0 R28");
    check(cpu.r[27]==8195, "MOVCFU_len0 R27");

    // ---- MOVCUh l1=0,l2=2: halfword no copy, R28=op1, R27=op2 ----
    clear_ram();
    put_el(8192, 16'haabb);
    run_case(8'h5a, 8'h08, 4096, 8192, 0, 2, 16'h0000);
    check(cpu.r[28]==4096, "MOVCUh_len0 R28");
    check(cpu.r[27]==8192, "MOVCUh_len0 R27");

    // ---- MOVCDh l1=1,l2=1: one half, R28=op1-2, R27=op2-2 ----
    clear_ram();
    put_el(4096, 16'h1234);
    run_case(8'h5a, 8'h09, 4096, 8192, 1, 1, 16'h0000);
    check(gb(8192)==8'h34 && gb(8193)==8'h12, "MOVCDh_len1 copied");
    check(cpu.r[28]==4094, "MOVCDh_len1 R28");
    check(cpu.r[27]==8190, "MOVCDh_len1 R27");

    if (errors == 0) $display("V60 STRFS PASS");
    else             $display("V60 STRFS FAIL (%0d errors)", errors);
    $finish;
end
initial begin #5000000; $display("V60 STRFS FAIL (timeout)"); $finish; end
endmodule
