[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path -LiteralPath (Split-Path -Parent $PSScriptRoot)).Path
$commonPath = Join-Path $repoRoot "Arcade-SegaSystem32.qsf"
$orunnersPath = Join-Path $repoRoot "s32OutRunners.qsf"

$profile = @(
    "",
    "# OutRunners dedicated revision (Sega Multi 32).",
    "# Generated by tools/sync-outrunners-qsf.ps1; edit the shared QSF above.",
    "# The shared S32_SYSTEM32_ONLY macro is stripped from this revision:",
    "# Multi 32 needs the second palette/mixer bank, 128 KiB work RAM, and the",
    "# descriptor-led board profile that macro compiles out.",
    'set_global_assignment -name VERILOG_MACRO "S32_ORUNNERS_ONLY=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_MULTI32_ONLY=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_V60_NO_FP=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_RELEASE_MINIMAL=1"',
    'set_global_assignment -name VERILOG_MACRO "S32_JT12_MLAB_SHIFTS=1"',
    ""
) -join [Environment]::NewLine

$crlf = [string][char]13 + [string][char]10
$lf = [string][char]10
$common = [IO.File]::ReadAllText($commonPath).Replace($crlf, $lf)
# The shared project can temporarily carry another dedicated game's macro
# while that profile is being developed, and it always carries the
# single-screen System 32 restriction.  Neither may leak into the Multi 32
# OutRunners revision.
$common = (($common -split $lf) | Where-Object {
    $_ -notmatch 'VERILOG_MACRO\s+"S32_JPARK_ONLY=1"' -and
    $_ -notmatch 'VERILOG_MACRO\s+"S32_SYSTEM32_ONLY=1"'
}) -join $lf
$expected = $common.TrimEnd([char]13, [char]10) + $lf +
    $profile.Replace($crlf, $lf)
$current = if (Test-Path -LiteralPath $orunnersPath -PathType Leaf) {
    [IO.File]::ReadAllText($orunnersPath).Replace($crlf, $lf)
} else {
    ""
}

if ($current -cne $expected) {
    $temp = Join-Path $repoRoot ".s32OutRunners.qsf.tmp.$PID.$([Guid]::NewGuid().ToString('N'))"
    $backup = Join-Path $repoRoot ".s32OutRunners.qsf.backup.$PID.$([Guid]::NewGuid().ToString('N'))"
    try {
        [IO.File]::WriteAllText($temp, $expected, [Text.UTF8Encoding]::new($false))
        if (Test-Path -LiteralPath $orunnersPath -PathType Leaf) {
            [IO.File]::Replace($temp, $orunnersPath, $backup)
        }
        else {
            Move-Item -LiteralPath $temp -Destination $orunnersPath
        }
        $verified = [IO.File]::ReadAllText($orunnersPath).Replace($crlf, $lf)
        if ($verified -cne $expected) {
            throw "Atomic OutRunners QSF update did not verify byte-for-byte."
        }
    }
    finally {
        Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
        Remove-Item -LiteralPath $backup -Force -ErrorAction SilentlyContinue
    }
    Write-Host "Updated s32OutRunners.qsf atomically from Arcade-SegaSystem32.qsf."
}
else {
    Write-Host "s32OutRunners.qsf is current."
}
